/*
 * Ishaan Kejriwal - AP CSA
 * File: Animal.java
 * Description: Domain model for one animal location observation.
 * Date: 2026-04-22
 */

import java.time.LocalDateTime;
import java.util.UUID;

// Domain model representing one location observation record.
public class Animal {
    // Database surrogate key generated by MySQL.
    private Integer id;

    // Requested observation-tracking fields.
    private String animalType;
    private float latitude;
    private float longitude;
    private LocalDateTime observedAt;
    private int durationMinutes;
    private UUID observationUuid;
    private boolean revisited;

    // Legacy aliases kept so old classes still compile.
    private String name;
    private int age;
    private String species;

    // Primary constructor for observation records.
    public Animal(String animalType,
                  float latitude,
                  float longitude,
                  LocalDateTime observedAt,
                  int durationMinutes,
                  UUID observationUuid,
                  boolean revisited) {
        this.animalType = animalType;
        this.latitude = latitude;
        this.longitude = longitude;
        this.observedAt = observedAt;
        this.durationMinutes = durationMinutes;
        this.observationUuid = observationUuid;
        this.revisited = revisited;

        // Keep legacy values synchronized to avoid breaking old code paths.
        this.name = animalType;
        this.age = durationMinutes;
        this.species = animalType;
    }

    // Legacy constructor retained for compatibility with Cat/Dog classes.
    public Animal(String name, int age, String species) {
        this(
                species == null || species.isBlank() ? "Unknown" : species,
                0.0f,
                0.0f,
                LocalDateTime.now(),
                Math.max(0, age),
                UUID.randomUUID(),
                false
        );
        this.name = name;
        this.age = age;
        this.species = species;
    }

    public Animal(String name, int age) {
        this(name, age, "Unknown");
    }

    public Animal() {
        this("Unknown", 0, "Unknown");
    }

    // Optional sound method used by legacy UI and examples.
    public String makeSound() {
        return "N/A";
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getAnimalType() {
        return animalType;
    }

    public void setAnimalType(String animalType) {
        this.animalType = animalType;
        this.name = animalType;
        this.species = animalType;
    }

    public float getLatitude() {
        return latitude;
    }

    public void setLatitude(float latitude) {
        this.latitude = latitude;
    }

    public float getLongitude() {
        return longitude;
    }

    public void setLongitude(float longitude) {
        this.longitude = longitude;
    }

    public LocalDateTime getObservedAt() {
        return observedAt;
    }

    public void setObservedAt(LocalDateTime observedAt) {
        this.observedAt = observedAt;
    }

    public int getDurationMinutes() {
        return durationMinutes;
    }

    public void setDurationMinutes(int durationMinutes) {
        this.durationMinutes = durationMinutes;
        this.age = durationMinutes;
    }

    public UUID getObservationUuid() {
        return observationUuid;
    }

    public void setObservationUuid(UUID observationUuid) {
        this.observationUuid = observationUuid;
    }

    public boolean isRevisited() {
        return revisited;
    }

    public void setRevisited(boolean revisited) {
        this.revisited = revisited;
    }

    // Compatibility accessors.
    public String getName() {
        return name;
    }

    public int getAge() {
        return age;
    }

    public String getSpecies() {
        return species;
    }

    public void setName(String name) {
        this.name = name;
        this.animalType = name;
    }

    public void setAge(int age) {
        this.age = age;
        this.durationMinutes = Math.max(0, age);
    }

    public void setSpecies(String species) {
        this.species = species;
        this.animalType = species;
    }

    @Override
    public String toString() {
        return "Animal{" +
                "id=" + id +
                ", animalType='" + animalType + '\'' +
                ", latitude=" + latitude +
                ", longitude=" + longitude +
                ", observedAt=" + observedAt +
                ", durationMinutes=" + durationMinutes +
                ", observationUuid=" + observationUuid +
                ", revisited=" + revisited +
                '}';
    }
}
