// Abstract base model shared by all animal types.
public abstract class Animal {
    // Database identifier generated by MySQL.
    private Integer id;

    // Animal display name.
    private String name;

    // Animal age in years.
    private int age;

    // Species descriptor used for fallback classification.
    private String species;

    // Creates an animal with explicit name, age, and species.
    public Animal(String name, int age, String species) {
        this.name = name;
        this.age = age;
        this.species = species;
    }

    // Creates an animal with unknown species.
    public Animal(String name, int age) {
        this(name, age, "Unknown");
    }

    // Creates a placeholder animal with default values.
    public Animal() {
        this("Unnamed", 0, "Unknown");
    }

    // Returns the sound produced by the concrete animal type.
    public abstract String makeSound();

    // Returns the animal name.
    public String getName() {
        return name;
    }

    // Returns the database identifier.
    public Integer getId() {
        return id;
    }

    // Returns the age in years.
    public int getAge() {
        return age;
    }

    // Returns the species label.
    public String getSpecies() {
        return species;
    }

    // Updates the animal name.
    public void setName(String name) {
        this.name = name;
    }

    // Sets the database identifier.
    public void setId(Integer id) {
        this.id = id;
    }

    // Updates the age in years.
    public void setAge(int age) {
        this.age = age;
    }

    // Updates the species label.
    public void setSpecies(String species) {
        this.species = species;
    }

    @Override
    public String toString() {
        return "Animal{" + "id=" + id + ", name='" + name + '\'' + ", age=" + age + ", species='" + species + '\'' + '}';
    }
}
